---
title: "Program"
---

<div class="container" style="min-height:75vh;">

<h1>Program</h1>

<h2>What you will learn</h2>

You will learn how to build your own packages for visualisations using [htmlwidgets](http://www.htmlwidgets.org/). htmlwidgets is the backbone of packages such as [leaflet](https://rstudio.github.io/leaflet/), [plotly](https://plotly.com/r/), [highcharter](http://jkunst.com/highcharter/), and many others. The aim is that by the end of the workshop you will be able to write your own such packages!

<h2>Methodology</h2>

Learn by doing. I believe this remains the best way to go about it; the workshop will therefore have you write a quite a bit of code.

<h2>Plan</h2>

This is a rough plan, things are likely to change depending on the pace we pick up. The point is not to rush things but if great progress is made, we can delve into more advanced stuff at the end.

<ul class="collection with-header">
<li class="collection-item"><p>Introduction to the basics (20-30 mins)</p></li>
<li class="collection-item"><p>Explore htmlwidgets (45-60 mins)</p></li>
<li class="collection-item"><p>Coffee Break</p></li>
<li class="collection-item"><p>Build our second widget (60 mins)</p></li>
<li class="collection-item"><p>Additional functionalities (30 mins)</p></li>
</ul>

</div>