---
title: "Prerequisites"
---

```{r, include = FALSE}
library(htmltools)
```

<div class="container" style="min-height:75vh;">

<h1>Prerequisites</h1>

You __do not__ need to know JavaScript to follow along.

<h2>Setup</h2>

There are two ways to follow along this workshop; from your local machine or from the remote RStudio Cloud projects.

```{r, echo=FALSE}
div(
  class = "row",
  div(
    class = "col m6",
    div(
      class = "card",
      div(
        class = "card-image",
        tags$img(src = "assets/img/laptop.png", class = "responsive-img"),
        h1(class = "card-title blue-text text-darken-1", "Local", span("_", class = "orange-text", .noWS = "before"))
      ),
      div(
        class = "card-content",
        p("Required:"),
        tags$ul(
          class = "collection",
          tags$li(
            class = "collection-item", "A recent installation of R (R >= 3.6.0)"
          ),
          tags$li(
            class = "collection-item", "A text editor or IDE you are comfortable with, e.g.: RStudio."
          ),
          tags$li(
            class = "collection-item", 
            "Packages devtools and htmlwidgets installed",
            tags$small(code('install.packages(c("devtools", "htmlwidgets"))'))
          ),
          tags$li(
            class = "collection-item", 
            "Clone or download", 
            tags$a(
              href = "https://github.com/JohnCoene/how-to-build-htmlwidgets",
              "github.com/JohnCoene/how-to-build-htmlwidgets"
            ),
            tags$small(code('git clone https://github.com/JohnCoene/how-to-build-htmlwidgets.git')),
          tags$li(
            class = "collection-item", 
            "Register for e-Rum and the workshop"
          )
          )
        )
      )
    )
  ),
  div(
    class = "col m6",
    div(
      class = "card",
      div(
        class = "card-image",
        tags$img(src = "assets/img/server.jpg", class = "responsive-img"),
        h1(class = "card-title blue-text text-darken-1", "Remote", span("_", class = "orange-text", .noWS = "before"))
      ),
      div(
        class = "card-content",
        p("Coming soon: will be up for the workshop.")
      )
    )
  )
)
```

</div>